public class ex {
    public static void main()
    {
        /*
        integer div;
        try
        {
        div=3/0;
        }
        catch(Mathexception e)
        {
            div=3/1;
            system.debug(div);
        }*/
       /* account a=new account();
        try
        {
        a.Id='7384287';
            insert a;
            system.debug('llll');
    }
        catch(exception e)
        {
            system.debug('prashant');
        }*/
        
    }

}